### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by liamwhite** [AisteruFire/Velvet#1]
This project should use a code linter such as [ESLint](http://eslint.org/) to ensure general consistency.

Optionally, you can also use [prettier](https://github.com/prettier/prettier) to ensure that all code will be formatted the exact same way no matter what.

**Comment by AisteruFire** [comment]
Thank you for the links, I didn't know these existed. I'll give it a shot

**Comment by AisteruFire** [comment]
So, I installed ESLint and gave it a try... I'm willing to try and change my habits, but I don't find it very useful here. Maybe I'm using it wrong.
Here's what is echoed me :
```
D:\Documents\Extensions Chrome\Velvet\scripts\afterSubmit.js
  8:1  error  Parsing error: The keyword 'const' is reserved

D:\Documents\Extensions Chrome\Velvet\scripts\beforeSubmit.js
  40:24  error  Parsing error: Unexpected token of

D:\Documents\Extensions Chrome\Velvet\scripts\constants.js
   7:5   error  'DEFAULT_QUICK_TAGS' is assigned a value but never used       no-unused-vars
   7:34  error  'DEFAULT_ALIASES' is assigned a value but never used          no-unused-vars
  10:5   error  'WELCOME_MESSAGE' is assigned a value but never used          no-unused-vars
  13:5   error  'QUICK_TAGS_BUTTON_TITLE' is assigned a value but never used  no-unused-vars

D:\Documents\Extensions Chrome\Velvet\scripts\functions.js
   7:10  error  'openSettings' is defined but never used            no-unused-vars
   9:1   error  Expected indentation of 1 tab but found 4 spaces    indent
   9:5   error  'chrome' is not defined                             no-undef
  10:1   error  Expected indentation of 2 tabs but found 8 spaces   indent
  12:1   error  Expected indentation of 2 tabs but found 8 spaces   indent
  13:1   error  Expected indentation of 3 tabs but found 12 spaces  indent
  15:1   error  Expected indentation of 2 tabs but found 8 spaces   indent
  15:9   error  'chrome' is not defined                             no-undef
  16:1   error  Expected indentation of 1 tab but found 4 spaces    indent

D:\Documents\Extensions Chrome\Velvet\scripts\openSettings.js
  8:49  error  Parsing error: Unexpected token >

D:\Documents\Extensions Chrome\Velvet\scripts\settings.js
  7:1  error  Parsing error: The keyword 'const' is reserved
```

Almost none of them are relevant : I don't understand the error with 'const' since it seems to work fine in other files, chrome being not defined is normal since it's specific to the browser, the constants being not used is because the .js file is included elsewhere and the unexpected tokens don't seem to bother when executing.

Am I missing something here ? As I said, I'm willing to try and change my ways, but I must admit that I kinda like coding with my notepad and my Chrome window x)

**Comment by liamwhite** [comment]
You have to tell ESLint that those are okay.

```yaml
# .eslintrc.yml
extends: eslint:recommended
env:
  browser: true
  es6: true

parserOptions:
  ecmaVersion: 6
  sourceType: script

# this is needed because you use concatenation
# instead of AMD/UMD
globals:
  DEFAULT_QUICK_TAGS: true
  DEFAULT_ALIASES: true
  WELCOME_MESSAGE: true
  QUICK_TAGS_BUTTON_TITLE: true
  openSettings: true
  chrome: true
```
